# Generated by Django 4.2.1 on 2023-05-28 14:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("places_service", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Place",
            new_name="Places",
        ),
    ]
