# Generated by Django 4.2.1 on 2023-05-28 14:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("places_service", "0002_rename_place_places"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Places",
            new_name="Place",
        ),
        migrations.AlterModelTable(
            name="place",
            table="places",
        ),
    ]
