# Generated by Django 4.2.1 on 2023-05-29 08:16

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("places_service", "0003_rename_places_place_alter_place_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="geom",
            field=django.contrib.gis.db.models.fields.PointField(
                db_index=True, srid=4326
            ),
        ),
    ]
